### ISSUE TITLE
Staking Not Active

### ISSUE THREAD

**Issue by lkhgw84** [Realbityoda/Aegeus#1]
check it out, please
aegeus-cli getstakingstatus
{
    "validtime" : true,
    "haveconnections" : true,
    "walletunlocked" : true,
    "mintablecoins" : false,
    "enoughcoins" : true,
    "mnsync" : true,
    "staking status" : false

aegeus-cli getinfo
{
    "version" : 1010101,
    "protocolversion" : 70813,
    "walletversion" : 61000,
    "balance" : 0.00000000,
    "obfuscation_balance" : 0.00000000,
    "blocks" : 137547,
    "timeoffset" : 0,
    "connections" : 16,
    "proxy" : "",
    "difficulty" : 1693766.31085340,
    "testnet" : false,
    "keypoololdest" : 1526786662,
    "keypoolsize" : 1001,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00010000,
    "staking status" : "Staking Not Active",
    "errors" : ""

masternode status
    "status" : 4,
    "message" : "Masternode successfully started"

**Comment by Realbityoda** [comment]
as you are holding a 0 bal you would not be staking ur masternode. :)

**Comment by Matrix8081** [comment]
I have 6000 coins in my wallet I'm seeing this same message "staking not active" how do I fix this? Ty

**Comment by Realbityoda** [comment]
Please contact support from AEG.

This is MN script.

Thank you.
